#ifndef __JGE_DISPLAYOBJECT_TYPE__
#define __JGE_DISPLAYOBJECT_TYPE__

enum JGE_DISPLAYOBJECT_TYPE
{
	JGE_DISPLAYOBJECT_DISPLAYOBJECT_TYPE, JGE_DISPLAYOBJECT_CONTAINER_TYPE, JGE_DISPLAYOBJECT_TEXT_TYPE
};

#endif